name: 'demo-mongodb-redis'

services:
  mongo-db:
    image: mongo:8.0.9
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
  redis-db:
    image: redis:8.0.0-alpine
    container_name: redis-db
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
